fix indentions

diff --git a/.github/workflows/feature.yml b/.github/workflows/feature.yml
--- a/.github/workflows/feature.yml
+++ b/.github/workflows/feature.yml
@@ -39,19 +39,19 @@ jobs:
           LAST_VERSION_PART_PREFIX=${LAST_VERSION_PART_PREFIX%.*}
         # If branch name starts with bugs; append b where it stands as BUGS
           if [[ $BRANCH_NAME == "fix"* ]]; then
-            NEW_LAST_VERSION_PART=${LAST_VERSION_PART_PREFIX}b${GITHUB_RUN_ID}
+               NEW_LAST_VERSION_PART=${LAST_VERSION_PART_PREFIX}b${GITHUB_RUN_ID}
         # If branch name starts with bugs; append f where it stands for FEEATURE
           elif [[ $BRANCH_NAME == "feature"* ]]; then
-            NEW_LAST_VERSION_PART=${LAST_VERSION_PART_PREFIX}f${GITHUB_RUN_ID}
+               NEW_LAST_VERSION_PART=${LAST_VERSION_PART_PREFIX}f${GITHUB_RUN_ID}
         # If branch name starts test; append RC on it
           elif [[ $BRANCH_NAME == "test"* ]]; then
-            NEW_LAST_VERSION_PART=${LAST_VERSION_PART_PREFIX}rc${GITHUB_RUN_ID}
+               NEW_LAST_VERSION_PART=${LAST_VERSION_PART_PREFIX}rc${GITHUB_RUN_ID}
         # If branch name starts with MAIN
           elif [[ $BRANCH_NAME == "main"* ]]; then
-            NEW_LAST_VERSION_PART=${LAST_VERSION_PART_PREFIX}${GITHUB_RUN_ID}
+               NEW_LAST_VERSION_PART=${LAST_VERSION_PART_PREFIX}${GITHUB_RUN_ID}
           else
-            echo "Invalid branch name"
-            exit 1
+               echo "Invalid branch name"
+               exit 1
           fi
           NEW_VERSION=${VERSION%.*}.${NEW_LAST_VERSION_PART}
           echo $NEW_VERSION
