added condition depending on the branch name

diff --git a/.github/workflows/feature.yml b/.github/workflows/feature.yml
--- a/.github/workflows/feature.yml
+++ b/.github/workflows/feature.yml
@@ -30,11 +30,29 @@ jobs:
           poetry-version: "1.3.2"
       - name: Increment version
         run: |
+        # Gets the branch name
+          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
+        # Create versioning
           VERSION=$(poetry version --short)
           LAST_VERSION_PART=${VERSION#*.}
           LAST_VERSION_PART_PREFIX=${LAST_VERSION_PART%??}
           LAST_VERSION_PART_PREFIX=${LAST_VERSION_PART_PREFIX%.*}
-          NEW_LAST_VERSION_PART=${LAST_VERSION_PART_PREFIX}rc${GITHUB_RUN_ID}
+        # If branch name starts with bugs; append b where it stands as BUGS
+          if [[ $BRANCH_NAME == "bugs"* ]]; then
+            NEW_LAST_VERSION_PART=${LAST_VERSION_PART_PREFIX}b${GITHUB_RUN_ID}
+        # If branch name starts with bugs; append f where it stands for FEEATURE
+          elif [[ $BRANCH_NAME == "feature"* ]]; then
+            NEW_LAST_VERSION_PART=${LAST_VERSION_PART_PREFIX}f${GITHUB_RUN_ID}
+        # If branch name starts test; append RC on it
+          elif [[ $BRANCH_NAME == "test"* ]]; then
+            NEW_LAST_VERSION_PART=${LAST_VERSION_PART_PREFIX}rc${GITHUB_RUN_ID}
+        # If branch name starts with MAIN
+          elif [[ $BRANCH_NAME == "main"* ]]; then
+            NEW_LAST_VERSION_PART=${LAST_VERSION_PART_PREFIX}${GITHUB_RUN_ID}
+          else
+            echo "Invalid branch name"
+            exit 1
+          fi
           NEW_VERSION=${VERSION%.*}.${NEW_LAST_VERSION_PART}
           echo $NEW_VERSION
           echo "::set-output name=version::$NEW_VERSION"
